Markup/#2
RollingInTheDeep/RID-Project pull request #5
Opened 2021-05-07 14:14 UTC by Da-yun

홈뷰 구현

2021-05-08 08:38 UTC, OMEGA-Y requested changes
전반적으로 고생하셨습니다! commit 메시지랑 review한 것 위주로 수정 부탁드려요!

2021-05-08 08:38 UTC, OMEGA-Y commented on app/src/main/java/com/example/rid_project/MainActivity.java
> +    private BottomNavigationFragment fragment_Bottom;  //  하단 프래그먼트
변수명은 camelCase로 작성해주세요
`fragmentBottom` 이런식으로 아래 변수도 수정 부탁드립니다

그리고 하단 프래그먼트보다는 `fragmentNavBar` 이런식으로 작명하는게 좀 더 나중에 알아보기 쉬울 것 같습니다. 설명 없이 변수명만으로도 이게 뭔지 알 수 있으면 좋을 것 같아요

2021-05-08 08:38 UTC, OMEGA-Y commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/fragment_main_bottom"
여기도 id 이름을 bottom보다는 navigationbar라는 의미가 되도록 바꿔주시면 좋을 것 같습니다!

2021-05-08 08:38 UTC, OMEGA-Y commented on app/src/main/res/layout/bookitem_main.xml
> +            android:id="@+id/book_name"
what_where_description 형태로 id 이름 수정 해주세요!

2021-05-08 08:38 UTC, OMEGA-Y commented on app/src/main/res/layout/fragment_main.xml
> +                android:id="@+id/plusButton_main"
`imageButton_main_plus` 이렇게 하는게 convention에 더 맞는 것 같습니다

2021-05-08 08:38 UTC, OMEGA-Y commented on app/src/main/res/layout/fragment_main.xml
> +            android:id="@+id/textView2"
id convention에 맞게 수정해주세요

2021-05-08 11:21 UTC, Da-yun commented on app/src/main/res/layout/fragment_main.xml
> +            android:id="@+id/textView2"
엇 이거 잘못들어갔었네용 감사함당ㅎㅎ

2021-05-09 02:49 UTC, OMEGA-Y commented on app/src/main/java/com/example/rid_project/MainActivity.java
> +    private BottomNavigationFragment fragmentBottom;  //  Fragment NavBar
주석뿐만 아니라 fragmentBottom -> fragmentNavBar 이런식으로 직관적으로 변수명을 바꾸면 좋을 것 같습니다!

2021-05-09 02:54 UTC, OMEGA-Y commented
나머지는 잘 수정해주신 것 같고, commit만 한 개로 합쳐주시면 깔끔할 것 같습니다.
ex. `[#2] markup - HomeView xml`

2021-05-10 12:37 UTC, merged